#!/bin/sh
IF="$1"
echo "PPP down on $IF, cleaning up..."

if [ -f /var/run/mqtt_to_sqlite.pid ]; then
  kill "$(cat /var/run/mqtt_to_sqlite.pid)" 2>/dev/null
  rm -f /var/run/mqtt_to_sqlite.pid
fi

exit 0
