#!/bin/sh
# Arguments: interface tty speed localIP remoteIP ipparam
IF="$1"
CONFIG=/mod/etc/conf/esp32c3.cfg

[ -r "$CONFIG" ] && . "$CONFIG"

echo "ESP32-C3 PPP up on $IF"
if [ -n "$ROUTE_NET" ] && [ -n "$PPP_REMOTE_IP" ]; then
  /sbin/ip route replace "$ROUTE_NET" via "$PPP_REMOTE_IP" dev "$IF"
fi

exit 0
