$(call PKG_INIT_BIN, 1.0.9)

$(PKG)_SOURCE:=
$(PKG)_SITE:=none

$(PKG)_DEPENDS_ON += sqlite

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MQTT_GRAFANA_TOPIC
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MQTT_GRAFANA_DB_PATH
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MQTT_GRAFANA_MAX_ROWS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_MQTT_GRAFANA_ALLOWED_IP

MQTT_GRAFANA_FILESDIR := $($(PKG)_TARGET_DIR)
MQTT_GRAFANA_BINARY   := $(MQTT_GRAFANA_FILESDIR)/mqtt-grafana.cgi
MQTT_GRAFANA_ROOTDIR  := $($(PKG)_DEST_DIR)
MQTT_GRAFANA_TARGET   := $(MQTT_GRAFANA_ROOTDIR)/usr/mww/cgi-bin/mqtt-grafana.cgi
MQTT_GRAFANA_WEB_SRC  := $(MQTT_GRAFANA_FILESDIR)/mqtt-grafana.html
MQTT_GRAFANA_WEB      := $(MQTT_GRAFANA_ROOTDIR)/usr/mww/mqtt-grafana.html

$(MQTT_GRAFANA_BINARY): $(PACKAGES_DIR)/.$(pkg)-$($(PKG)_VERSION)
	@test -f "$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/sqlite3.h" || { \
		echo "ERROR: sqlite3.h was not found in the target staging directory."; \
		exit 1; \
	}
	$(MAKE_ENV) $(TARGET_CC) $(TARGET_CFLAGS) -std=gnu99 -Wall -Wextra \
		-I$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include \
		-I$(TARGET_TOOLCHAIN_STAGING_DIR)/include \
		-DDEFAULT_GRAFANA_TOPIC=\"$(call qstrip,$(FREETZ_PACKAGE_MQTT_GRAFANA_TOPIC))\" \
		-DDEFAULT_DB_PATH=\"$(call qstrip,$(FREETZ_PACKAGE_MQTT_GRAFANA_DB_PATH))\" \
		-DDEFAULT_MAX_ROWS=$(FREETZ_PACKAGE_MQTT_GRAFANA_MAX_ROWS) \
		-DDEFAULT_ALLOWED_IP=\"$(call qstrip,$(FREETZ_PACKAGE_MQTT_GRAFANA_ALLOWED_IP))\" \
		$(MQTT_GRAFANA_FILESDIR)/mqtt-grafana.c \
		-o $@ \
		-Wl,-rpath,/usr/lib/freetz \
		-L$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib \
		-L$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/freetz \
		-lsqlite3 -lm

$(MQTT_GRAFANA_TARGET): $(MQTT_GRAFANA_BINARY)
	@mkdir -p $(dir $@)
	cp -f $< $@
	[ "$(FREETZ_SEPARATE_AVM_UCLIBC)" != "y" ] || \
		$(PATCHELF_TARGET) --set-interpreter $(FREETZ_LIBRARY_DIR)/ld-uClibc.so.1 $@
	$(TARGET_STRIP) $@

$(MQTT_GRAFANA_WEB): $(MQTT_GRAFANA_WEB_SRC)
	@mkdir -p $(dir $@)
	cp -f $< $@

$(pkg)-precompiled: $(MQTT_GRAFANA_TARGET) $(MQTT_GRAFANA_WEB)

$(PKG_FINISH)
