$(call PKG_INIT_BIN, 1.1.3)

$(PKG)_SOURCE :=
$(PKG)_SITE   := none

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_SERIAL_DEVICE
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_SERIAL_BAUD
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_PPP_LOCAL_IP
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_PPP_REMOTE_IP
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_PPP_DNS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_ROUTE_NET
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_BROKER
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_PORT
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_TOPICS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_DB_PATH
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_CLIENT_ID
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_NETWORK_FIX_SCRIPT
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_RECONNECT_MIN_S
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_RECONNECT_MAX_S
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_RETRY_SLEEP_AFTER_SCRIPT_S
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_MQTT_LOG_INSERTS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_GRAFANA_TOPIC
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_GRAFANA_MAX_ROWS
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_ESP32C3_GRAFANA_ALLOWED_IP

ESP32C3_DEFAULTDIR := $($(PKG)_DEST_DIR)/etc/default.esp32
ESP32C3_INITDIR    := $($(PKG)_DEST_DIR)/etc/init.d
ESP32C3_TARGET     := $(ESP32C3_INITDIR)/rc.esp32c3

$(ESP32C3_TARGET): $(PACKAGES_DIR)/.$(pkg)-$($(PKG)_VERSION)
	$(SED) -i \
		-e 's|@SERIAL_DEVICE@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_SERIAL_DEVICE))|g' \
		-e 's|@SERIAL_BAUD@|$(FREETZ_PACKAGE_ESP32C3_SERIAL_BAUD)|g' \
		-e 's|@PPP_LOCAL_IP@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_PPP_LOCAL_IP))|g' \
		-e 's|@PPP_REMOTE_IP@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_PPP_REMOTE_IP))|g' \
		-e 's|@PPP_DNS@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_PPP_DNS))|g' \
		-e 's|@ROUTE_NET@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_ROUTE_NET))|g' \
		-e 's|@MQTT_BROKER@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_MQTT_BROKER))|g' \
		-e 's|@MQTT_PORT@|$(FREETZ_PACKAGE_ESP32C3_MQTT_PORT)|g' \
		-e 's|@MQTT_TOPICS@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_MQTT_TOPICS))|g' \
		-e 's|@MQTT_DB_PATH@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_MQTT_DB_PATH))|g' \
		-e 's|@MQTT_CLIENT_ID@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_MQTT_CLIENT_ID))|g' \
		-e 's|@NETWORK_FIX_SCRIPT@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_NETWORK_FIX_SCRIPT))|g' \
		-e 's|@RECONNECT_MIN_S@|$(FREETZ_PACKAGE_ESP32C3_RECONNECT_MIN_S)|g' \
		-e 's|@RECONNECT_MAX_S@|$(FREETZ_PACKAGE_ESP32C3_RECONNECT_MAX_S)|g' \
		-e 's|@RETRY_SLEEP_AFTER_SCRIPT_S@|$(FREETZ_PACKAGE_ESP32C3_RETRY_SLEEP_AFTER_SCRIPT_S)|g' \
		-e 's|@MQTT_LOG_INSERTS@|$(if $(FREETZ_PACKAGE_ESP32C3_MQTT_LOG_INSERTS),1,0)|g' \
		-e 's|@GRAFANA_TOPIC@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_GRAFANA_TOPIC))|g' \
		-e 's|@GRAFANA_MAX_ROWS@|$(FREETZ_PACKAGE_ESP32C3_GRAFANA_MAX_ROWS)|g' \
		-e 's|@GRAFANA_ALLOWED_IP@|$(call qstrip,$(FREETZ_PACKAGE_ESP32C3_GRAFANA_ALLOWED_IP))|g' \
		$(ESP32C3_DEFAULTDIR)/esp32c3.cfg
	chmod 755 $@

$(pkg)-precompiled: $(ESP32C3_TARGET)

$(pkg)-uninstall:
	$(RM) \
		$(ESP32C3_DEFAULTDIR)/esp32c3.cfg \
		$(ESP32C3_DEFAULTDIR)/ip-up \
		$(ESP32C3_DEFAULTDIR)/ip-down \
		$(ESP32C3_TARGET)

$(PKG_FINISH)
