#!/bin/sh
# Arguments: interface tty speed localIP remoteIP ipparam
IF="$1"

# Only act on our ESP32 link if you use linkname/ipparam
# if [ "$IF" != "ppp0" ]; then exit 0; fi

echo "PPP up on $IF, adding routes..."

# Example route
/sbin/ip route replace 192.168.4.0/24 via 192.168.178.250 dev "$IF"

# If you need default route through PPP, add:
# /sbin/ip route replace default dev "$IF"

# Start mqtt_to_sqlite after routes are in place
export MQTT_BROKER=192.168.178.250
export MQTT_PORT=1883
export MQTT_TOPICS="+/power/get,+/energycounter/get"
export MQTT_DB_PATH=/var/media/ftp/Verbatim-STORENGO-01/mqtt_messages.db
export MQTT_CLIENT_ID=fritzbox-mqtt2sqlite
export NETWORK_FIX_SCRIPT=/bin/true
export RECONNECT_MIN_S=2
export RECONNECT_MAX_S=60
export RETRY_SLEEP_AFTER_SCRIPT_S=5
export MQTT_LOG_INSERTS=0
/usr/bin/mqtt_to_sqlite  &
echo $! > /var/run/mqtt_to_sqlite.pid

exit 0
